version: '3.3'
services:
  database:
    image: postgres:13
    container_name: 'e-journal_db'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_e-journal
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  my-db:
  postgresql:
  postgresql_data: